"""
Prompts module for patchAgent.
"""

from .system_messages import (
    PATCH_ANALYST_SYSTEM_MESSAGE,
    QC_CHECKER_SYSTEM_MESSAGE,
    SPIKE_ANALYST_SYSTEM_MESSAGE,
    PASSIVE_ANALYST_SYSTEM_MESSAGE,
)

__all__ = [
    "PATCH_ANALYST_SYSTEM_MESSAGE",
    "QC_CHECKER_SYSTEM_MESSAGE",
    "SPIKE_ANALYST_SYSTEM_MESSAGE",
    "PASSIVE_ANALYST_SYSTEM_MESSAGE",
]
